name: Daily Check-in

on:
  # 定时触发
  schedule:
    - cron: '10 06 * * *'
    - cron: '30 16 * * *'

  
  # 允许手动触发
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code from main branch
      uses: actions/checkout@v4
      with:
        # ref: main  # 指定分支名
        # 或者使用其他分支
        ref: llllistenlll-patch-1
        # ref: develop
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run check-in script
      run: python ./main.py
      env:
        TZ: 'Asia/Shanghai'
        IKUUU_EMAIL: ${{ secrets.IKUUU_EMAIL }}
        IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
